#!/usr/bin/env python3
"""SoC component of the Cyclone 10 LP RefKit SoC demo"""
# pylint: disable=invalid-name

import argparse

from litex.soc.integration.builder import (Builder, builder_argdict,
                                           builder_args)
from litex.soc.integration.soc_sdram import soc_sdram_argdict, soc_sdram_args
from litex_boards.targets.c10lprefkit import BaseSoC

SYS_CLK_FREQ = 50000000


def parse_args():
    """Parse CLI arguments"""
    parser = argparse.ArgumentParser(
        description="Demo SoC and application for the Cyclone 10 LP RefKit"
    )
    parser.add_argument("--build", action="store_true", help="Build bitstream")

    builder_args(parser)
    soc_sdram_args(parser)

    return parser.parse_args()


def main():
    """Entry point"""
    args = parse_args()

    soc = BaseSoC(sys_clk_freq=SYS_CLK_FREQ, **soc_sdram_argdict(args))
    builder = Builder(soc, **builder_argdict(args))

    builder.build(run=args.build)


if __name__ == "__main__":
    main()
