#!/usr/bin/env python3
"""SoC component of the Cyclone 10 LP RefKit SoC demo"""
# pylint: disable=invalid-name


def main():
    """Entry point"""
    print("Hello World!")


if __name__ == "__main__":
    main()
